apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
      # Best practice: Service Account con acceso a S3 (IRSA)
      annotations:
        # Con el número de cuenta AWS
        eks.amazonaws.com/role-arn: arn:aws:iam::REDACTED_ACCOUNT_ID:role/MLflowS3AccessRole
    spec:
      serviceAccountName: mlflow-sa 
      containers:
        - name: mlflow
          # Usa la imagen de ECR o una pública oficial
          image: ghcr.io/mlflow/mlflow:v2.10.0 
          command:
            - "mlflow"
            - "server"
            - "--backend-store-uri"
            - "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):5432/$(POSTGRES_DB)"
            - "--default-artifact-root"
            # El bucle real
            - "s3://hotel-mlops-artifacts-prod/mlflow"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "5000"
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: mlops-secrets
            - configMapRef:
                name: mlops-config
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer # AWS provisionará un Classic/Network Load Balancer